# Generated by Django 4.2.7 on 2023-12-02 14:36

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='no_user.jpeg', upload_to=users.models.CustomUser.image_upload_to),
        ),
    ]
