# Generated by Django 4.2.7 on 2023-12-01 20:58

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_article_image_alter_articleseries_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='images.png', max_length=255, upload_to=main.models.Article.image_upload_to),
        ),
        migrations.AlterField(
            model_name='articleseries',
            name='image',
            field=models.ImageField(default='images.png', max_length=255, upload_to=main.models.articleSeries.image_upload_to),
        ),
    ]
