# Generated by Django 4.2.7 on 2023-12-04 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_content_article_about_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published'], 'verbose_name_plural': 'students'},
        ),
        migrations.AlterModelOptions(
            name='articleseries',
            options={'ordering': ['-published'], 'verbose_name_plural': 'Departments'},
        ),
    ]
