# Generated by Django 4.2.7 on 2023-12-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_article_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleseries',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='dept'),
        ),
    ]
