# Generated by Django 4.2.7 on 2023-12-04 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0018_alter_articleseries_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published'], 'verbose_name_plural': 'Article'},
        ),
        migrations.AlterModelOptions(
            name='articleseries',
            options={'ordering': ['-published'], 'verbose_name_plural': 'Series'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='name_slug',
            new_name='article_slug',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='about',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='lastname',
            new_name='subtitle',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='firstname',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='articleseries',
            old_name='abbr',
            new_name='subtitle',
        ),
        migrations.RenameField(
            model_name='articleseries',
            old_name='dept_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='article',
            name='dept',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='notes',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='series',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.articleseries', verbose_name='Series'),
        ),
        migrations.AddField(
            model_name='articleseries',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articleseries',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Series slug'),
        ),
    ]
